version: '3'
services:
  apicpts:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    image: python
    restart: always
    container_name: cpts_api_full
    environment:
      - TZ=Europe/Paris
    networks:
      - default
      - cptsnet
    external_links:
      - dbcpts
    command: >
      uvicorn main:main
      --host 0.0.0.0
      --port 8001
  
networks:
  cptsnet:
    external: true
